name: update requirements and clean unused images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Get .env file
        uses: xom9ikk/dotenv@v2.1.0
        with:
          path: .github
          load_mode: strict
      - name: install pur
        run: pip install pur
      - name: Update requirements.txt
        if: ${{ env.WORKFLOW_TYPE == 'netlify'}}
        run: pur -r requirements.txt --skip obsidiantools
      - name: Update requirements.txt
        if: ${{ env.WORKFLOW_TYPE != 'netlify'}}
        run: pur -r requirements.txt
      - name: check python cache
        id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
      - if: steps.python_cache.outputs.cache-hit != 'true'
        name: Recreate python cache
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - if: ${{ env.CLEAN == 'true' && env.DRY_RUN == 'false' }} 
        name: Remove unused media
        run: python find_unused_media.py "$IMG_DIR"
      - if: ${{ env.CLEAN == 'true' && env.DRY_RUN == 'true' }}
        name: Find unused media (dry run)
        run: python find_unused_media.py "$IMG_DIR" --dry-run
      - name: commit the new change (if found)
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git commit -am "Update requirements & remove unused media"
          git push
